set_property PACKAGE_PIN T24 [get_ports CLK_IN1_D_clk_p]
set_property PACKAGE_PIN U24 [get_ports CLK_IN1_D_clk_n]

set_property PACKAGE_PIN N26 [get_ports rst]
set_property PACKAGE_PIN AA23 [get_ports SYNC]
set_property PACKAGE_PIN AF15 [get_ports SYSREF]
set_property PACKAGE_PIN K10 [get_ports scramble_enable]
set_property PACKAGE_PIN B9 [get_ports serial_data]
set_property PACKAGE_PIN AF14 [get_ports test_enable]
set_property PACKAGE_PIN J15 [get_ports {sample[11]}]
set_property PACKAGE_PIN J14 [get_ports {sample[10]}]
set_property PACKAGE_PIN J13 [get_ports {sample[9]}]
set_property PACKAGE_PIN H13 [get_ports {sample[8]}]
set_property PACKAGE_PIN E11 [get_ports {sample[7]}]
set_property PACKAGE_PIN E10 [get_ports {sample[6]}]
set_property PACKAGE_PIN D11 [get_ports {sample[5]}]
set_property PACKAGE_PIN D10 [get_ports {sample[4]}]
set_property PACKAGE_PIN B10 [get_ports {sample[3]}]
set_property PACKAGE_PIN A10 [get_ports {sample[2]}]
set_property PACKAGE_PIN H11 [get_ports {sample[1]}]
set_property PACKAGE_PIN G11 [get_ports {sample[0]}]
set_property PACKAGE_PIN W21 [get_ports {state_out_0[1]}]
set_property PACKAGE_PIN AC16 [get_ports {state_out_0[0]}]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports CLK_IN1_D_clk_p]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports CLK_IN1_D_clk_n]
set_property IOSTANDARD LVCMOS18 [get_ports SYNC]
set_property IOSTANDARD LVCMOS18 [get_ports SYSREF]
set_property IOSTANDARD LVCMOS18 [get_ports rst]
set_property IOSTANDARD LVCMOS18 [get_ports scramble_enable]
set_property IOSTANDARD LVCMOS18 [get_ports serial_data]
set_property IOSTANDARD LVCMOS18 [get_ports test_enable]
set_property IOSTANDARD LVCMOS18 [get_ports {sample[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {sample[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {sample[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {sample[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {sample[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {sample[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {sample[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {sample[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {sample[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {sample[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {sample[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {sample[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {state_out_0[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {state_out_0[0]}]




create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list transmitter_i/clk_wiz/inst/clk_out1]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 2 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {transmitter_i/state_out_0[0]} {transmitter_i/state_out_0[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 2 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {state_out_0_OBUF[0]} {state_out_0_OBUF[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list transmitter_i/CGS_Generator_CGS_complete]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list transmitter_i/ILAS_generator_ILA_last]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list transmitter_i/local_clock_generator_character_clk]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list transmitter_i/local_clock_generator_multiframe_end]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list transmitter_i/serial_data]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list transmitter_i/sync_decoder/sync]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list transmitter_i/sync_decoder_0_sync_request]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list transmitter_i/transmitter_state_0_enable_ILAS]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list transmitter_i/transmitter_state_enlable_CGS]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list transmitter_i/util_vector_logic_0_Res_0]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_clk_out1]
