# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/test_fpga.xdc

# Block Designs: bd/transmitter/transmitter.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==transmitter || ORIG_REF_NAME==transmitter} -quiet] -quiet

# IP: bd/transmitter/ip/transmitter_local_clock_generator_0_0/transmitter_local_clock_generator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==transmitter_local_clock_generator_0_0 || ORIG_REF_NAME==transmitter_local_clock_generator_0_0} -quiet] -quiet

# IP: bd/transmitter/ip/transmitter_scrambler_0_1/transmitter_scrambler_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==transmitter_scrambler_0_1 || ORIG_REF_NAME==transmitter_scrambler_0_1} -quiet] -quiet

# IP: bd/transmitter/ip/transmitter_transmitter_state_0_0/transmitter_transmitter_state_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==transmitter_transmitter_state_0_0 || ORIG_REF_NAME==transmitter_transmitter_state_0_0} -quiet] -quiet

# IP: bd/transmitter/ip/transmitter_ILAS_generator_0_1/transmitter_ILAS_generator_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==transmitter_ILAS_generator_0_1 || ORIG_REF_NAME==transmitter_ILAS_generator_0_1} -quiet] -quiet

# IP: bd/transmitter/ip/transmitter_CGS_Generator_0_0/transmitter_CGS_Generator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==transmitter_CGS_Generator_0_0 || ORIG_REF_NAME==transmitter_CGS_Generator_0_0} -quiet] -quiet

# IP: bd/transmitter/ip/transmitter_MUX_3x1_0_0/transmitter_MUX_3x1_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==transmitter_MUX_3x1_0_0 || ORIG_REF_NAME==transmitter_MUX_3x1_0_0} -quiet] -quiet

# IP: bd/transmitter/ip/transmitter_MUX_3x1_1_0/transmitter_MUX_3x1_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==transmitter_MUX_3x1_1_0 || ORIG_REF_NAME==transmitter_MUX_3x1_1_0} -quiet] -quiet

# IP: bd/transmitter/ip/transmitter_encoder_wrapper_0_0/transmitter_encoder_wrapper_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==transmitter_encoder_wrapper_0_0 || ORIG_REF_NAME==transmitter_encoder_wrapper_0_0} -quiet] -quiet

# IP: bd/transmitter/ip/transmitter_single_ADC_frame_map_0_0/transmitter_single_ADC_frame_map_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==transmitter_single_ADC_frame_map_0_0 || ORIG_REF_NAME==transmitter_single_ADC_frame_map_0_0} -quiet] -quiet

# IP: bd/transmitter/ip/transmitter_sync_decoder_0_0/transmitter_sync_decoder_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==transmitter_sync_decoder_0_0 || ORIG_REF_NAME==transmitter_sync_decoder_0_0} -quiet] -quiet

# IP: bd/transmitter/ip/transmitter_serializer_0_0/transmitter_serializer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==transmitter_serializer_0_0 || ORIG_REF_NAME==transmitter_serializer_0_0} -quiet] -quiet

# IP: bd/transmitter/ip/transmitter_ADC_pattern_generator_0_0/transmitter_ADC_pattern_generator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==transmitter_ADC_pattern_generator_0_0 || ORIG_REF_NAME==transmitter_ADC_pattern_generator_0_0} -quiet] -quiet

# IP: bd/transmitter/ip/transmitter_alignment_substituti_0_1/transmitter_alignment_substituti_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==transmitter_alignment_substituti_0_1 || ORIG_REF_NAME==transmitter_alignment_substituti_0_1} -quiet] -quiet

# IP: bd/transmitter/ip/transmitter_MUX_2x1_0_0/transmitter_MUX_2x1_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==transmitter_MUX_2x1_0_0 || ORIG_REF_NAME==transmitter_MUX_2x1_0_0} -quiet] -quiet

# IP: bd/transmitter/ip/transmitter_clk_wiz_0_0/transmitter_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==transmitter_clk_wiz_0_0 || ORIG_REF_NAME==transmitter_clk_wiz_0_0} -quiet] -quiet

# IP: bd/transmitter/ip/transmitter_util_vector_logic_0_0/transmitter_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==transmitter_util_vector_logic_0_0 || ORIG_REF_NAME==transmitter_util_vector_logic_0_0} -quiet] -quiet

# XDC: c:/Users/lorin/git/UGent-Masterproef-JESD204/UGent-Masterproef-JESD204.gen/sources_1/bd/transmitter/transmitter_ooc.xdc
