# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/lorin/git/UGent-Masterproef-JESD204/UGent-Masterproef-JESD204.srcs/sources_1/bd/transmitter/ip/transmitter_clk_wiz_0_0/transmitter_clk_wiz_0_0.xci
# IP: The module: 'transmitter_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/lorin/git/UGent-Masterproef-JESD204/UGent-Masterproef-JESD204.gen/sources_1/bd/transmitter/ip/transmitter_clk_wiz_0_0/transmitter_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'transmitter_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/lorin/git/UGent-Masterproef-JESD204/UGent-Masterproef-JESD204.gen/sources_1/bd/transmitter/ip/transmitter_clk_wiz_0_0/transmitter_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'transmitter_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/lorin/git/UGent-Masterproef-JESD204/UGent-Masterproef-JESD204.gen/sources_1/bd/transmitter/ip/transmitter_clk_wiz_0_0/transmitter_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'transmitter_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/lorin/git/UGent-Masterproef-JESD204/UGent-Masterproef-JESD204.srcs/sources_1/bd/transmitter/ip/transmitter_clk_wiz_0_0/transmitter_clk_wiz_0_0.xci
# IP: The module: 'transmitter_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/lorin/git/UGent-Masterproef-JESD204/UGent-Masterproef-JESD204.gen/sources_1/bd/transmitter/ip/transmitter_clk_wiz_0_0/transmitter_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'transmitter_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/lorin/git/UGent-Masterproef-JESD204/UGent-Masterproef-JESD204.gen/sources_1/bd/transmitter/ip/transmitter_clk_wiz_0_0/transmitter_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'transmitter_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/lorin/git/UGent-Masterproef-JESD204/UGent-Masterproef-JESD204.gen/sources_1/bd/transmitter/ip/transmitter_clk_wiz_0_0/transmitter_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'transmitter_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
